import defaultComponents from "fumadocs-ui/mdx"
import * as ObsidianComponents from "fumadocs-obsidian/ui"
import { APIPage } from "@/components/api-page"
import * as PythonComponents from "fumadocs-python/components"
import { Callout } from "fumadocs-ui/components/callout"
import { Files, Folder, File } from "fumadocs-ui/components/files"
import { TypeTable } from "fumadocs-ui/components/type-table"
import { ImageZoom } from "fumadocs-ui/components/image-zoom"
import { InlineTOC } from "fumadocs-ui/components/inline-toc"
import { GithubInfo } from "fumadocs-ui/components/github-info"
import type { MDXComponents } from "mdx/types"
import Link from "next/link"
import { ComponentPreview } from "@/components/component-preview"
import { FeedbackBlock } from "@/components/feedback/client"
import { onBlockFeedbackAction } from "@/lib/github"
import { CalendarMinMaxDemo } from "@/components/demos/calendar-min-max-demo"
import { CalendarUnavailableDemo } from "@/components/demos/calendar-unavailable-demo"
import {
  Tab,
  Tabs as FumadocsTabs,
  TabsList as FumadocsTabsList,
  TabsTrigger as FumadocsTabsTrigger,
  TabsContent as FumadocsTabsContent,
} from "@/components/mdx-tabs"
import {
  Tip,
  Warning,
  Info,
  Note,
  Check,
  Step,
  Steps,
  Accordion as FumadocsAccordion,
  Accordions as FumadocsAccordions,
  AccordionGroup,
  Card as FumadocsCard,
  CardGroup as FumadocsCardGroup,
} from "@/components/mdx-compat"
// Registry demos: import via @/__registry__ for lazy-loading
// Direct demos: import directly when used as inline MDX children (not via ComponentPreview name=)
import {
  AvatarSizeDemo,
  AvatarFallbackDemo,
  AvatarGroupDemo,
  AvatarGitPlatformDemo,
  DiceBearAvatarDemo,
  ButtonDemo,
  CheckboxDemo,
  SwitchDemo,
  DialogDemo,
  InputBasicDemo,
  DatePickerDefaultDemo,
  DatePickerMinMaxDemo,
  ProgressBasicDemo,
  AnimatedCircularProgressBarDemo,
  DotPatternDemo,
  FlickeringGridDemo,
} from "@/__registry__"
import { AvatarSmartGroupDemo } from "@/components/avatar-smart-group-demo"
import { AvatarWithIconDemo } from "@/components/avatar-with-icon-demo"
import { InputOTPNumericDemo } from "@/components/demos/input-otp-numeric-demo"
import { CommandDialogDemo } from "@/components/demos/command-dialog-demo"
import { ContextMenuDemo } from "@/components/demos/context-menu-demo"
import { ContextMenuWithIconsDemo } from "@/components/demos/context-menu-with-icons-demo"
import { MacbookProDemo } from "@/components/demos/macbook-pro-demo"
import { SheetDemo } from "@/components/demos/sheet-demo"
import { SheetSideDemo } from "@/components/demos/sheet-side-demo"
import { SheetMobileDemo } from "@/components/demos/sheet-mobile-demo"
import { BasePopoverDemo } from "@/components/demos/base-popover-demo"
import { DialogSuccessDemo } from "@/components/demos/dialog-success-demo"
import { DialogDeactivateDemo } from "@/components/demos/dialog-deactivate-demo"
import { DialogPasswordDemo } from "@/components/demos/dialog-password-demo"
import { DialogShareDemo } from "@/components/demos/dialog-share-demo"
import {
  BadgeVariantsDemo,
  BadgeSizesDemo,
  BadgeIconDemo,
  BadgePillDemo,
  BadgeTableDemo,
  BadgeNotificationDemo,
  BadgeFeatureTagDemo,
} from "@/components/badge-demos"
import { AvatarSmartGroup } from "@nebutra/ui/primitives"
import { IconGallery } from "@/components/icon-gallery"
import { ColorPalette } from "@/components/color-palette"
import { ColorUsageDemos } from "@/components/color-usage"
import {
  TypographyHierarchyDemos,
  TypeScaleDemo,
  CJKWeightDemo,
} from "@/components/typography-demos"
import { BrandGradientsDemo } from "@/components/gradient-demos"
import { MotionDemos } from "@/components/motion-demos"
import { IntroductionHero } from "@/components/introduction-hero"
import {
  LogoShowcase,
  BrandPhilosophyVisual,
} from "@/components/brand-overview-visuals"
import {
  VisuallyHiddenDemo,
  FocusRingDemo,
  AriaPatternsDemo,
  MinTouchTargetDemo,
  PrefersReducedMotionDemo,
  ContrastRequirementsDemo,
  SkipLinkStyleDemo,
} from "@/components/accessibility-demos"
import {
  CopywritingErrorsDemo,
  CopywritingEmptyStateDemo,
  CopywritingSuccessDemo,
  CopywritingDestructiveDemo,
  CopywritingButtonsDemo,
  CopywritingProgressDemo,
  CopywritingCapitalizationDemo,
} from "@/components/copywriting-demos"
import { ThemeSwitcherDemo } from "@/components/previews/theme-switcher-demo"
import {
  ThemeColorsDemo,
  BrandOverridesDemo,
  ZIndexDemo,
} from "@/components/theming-demos"
import {
  StandardGridDemo,
  DashboardGridDemo,
  SplitLayoutDemo,
} from "@/components/grid-layout-demos"
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/mdx-resizable"
import { ScrollArea, ScrollBar } from "@/components/mdx-scroll-area"
import { Toggle, ToggleGroup, ToggleGroupItem } from "@/components/mdx-toggle"
import {
  HexGridDemo,
  DotPatternCardDemo,
  FlickeringGridCardDemo,
  WarpBackgroundDemo,
  StarsCanvasDemo,
  GlassmorphismDemo,
} from "@/components/pattern-demos"
import { GridDemo, GridCell } from "@/components/grid-demos"
import { Mermaid } from "fumadocs-mermaid/ui"
import { StatusBadge, DeprecatedBanner } from "@/components/status-badge"
import { FigmaLink } from "@/components/figma-link"

// Nebutra UI components (Globally injected into MDX)
import {
  Accordion as UIAccordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
  Alert,
  AlertTitle,
  AlertDescription,
  AlertIcon,
  AlertContent,
  AlertToolbar,
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
  Avatar,
  AvatarImage,
  AvatarFallback,
  AvatarGroup,
  GitHubAvatar,
  GitLabAvatar,
  BitbucketAvatar,
  AvatarWithIcon,
  DiceBearAvatar,
  Badge,
  Breadcrumb,
  BreadcrumbList,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbSeparator,
  BreadcrumbPage,
  BreadcrumbEllipsis,
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableRow,
  TableHead,
  TableCell,
  TableCaption,
  Button,
  ButtonLink,
  Checkbox,
  CheckboxGroup,
  ComboboxRoot,
  ComboboxInput,
  ComboboxOptionItem,
  ComboboxEmpty,
  ComboboxGroupSub,
  ComboboxSeparator as ComboboxSeparatorComp,
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
  DialogClose,
  DialogOverlay,
  DialogPortal,
  Input,
  Label,
  Select,
  SelectGroup,
  SelectValue,
  SelectTrigger,
  SelectContent,
  SelectLabel,
  SelectItem,
  SelectSeparator,
  Switch,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  Separator,
  Tooltip,
  TooltipTrigger,
  TooltipContent,
  TooltipProvider,
  ContextMenuRoot,
  ContextMenuTrigger,
  ContextMenuContent,
  ContextMenuGroup,
  ContextMenuItem,
  ContextMenuLabel,
  ContextMenuSeparator,
  Progress,
  Skeleton,
  Slider,
  Textarea,
  Sheet,
  SheetPortal,
  SheetOverlay,
  SheetTrigger,
  SheetClose,
  SheetContent,
  SheetHeader,
  SheetFooter,
  SheetTitle,
  SheetDescription,
  Drawer,
  DrawerPortal,
  DrawerOverlay,
  DrawerTrigger,
  DrawerClose,
  DrawerContent,
  DrawerHeader,
  DrawerFooter,
  DrawerTitle,
  DrawerDescription,
  Popover,
  PopoverTrigger,
  PopoverContent,
  PopoverAnchor,
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuCheckboxItem,
  DropdownMenuRadioItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuGroup,
  DropdownMenuPortal,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuRadioGroup,
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselPrevious,
  CarouselNext,
  Calendar,
  RangeCalendar,
  Command,
  CommandDialog,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandItem,
  CommandShortcut,
  CommandSeparator,
  CommandMenuRoot,
  CommandMenuInput,
  CommandMenuList,
  CommandMenuEmpty,
  CommandMenuGroup,
  CommandMenuItem,
  CommandMenuShortcut,
  CommandMenuSeparator,
  DatePicker,
  DateRangePicker,
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
  HoverCard,
  HoverCardTrigger,
  HoverCardContent,
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationLink,
  PaginationPrevious,
  PaginationNext,
  PaginationEllipsis,
  InputOTP,
  InputOTPGroup,
  InputOTPSlot,
  InputOTPSeparator,
  CardContent,
  NavigationMenu,
  NavigationMenuList,
  NavigationMenuItem,
  NavigationMenuContent,
  NavigationMenuTrigger,
  NavigationMenuLink,
  NavigationMenuIndicator,
  NavigationMenuViewport,
  navigationMenuTriggerStyle,
  Menubar,
  MenubarMenu,
  MenubarTrigger,
  MenubarContent,
  MenubarItem,
  MenubarSeparator,
  MenubarLabel,
  MenubarCheckboxItem,
  MenubarRadioGroup,
  MenubarRadioItem,
  MenubarShortcut,
  MenubarSub,
  MenubarSubTrigger,
  MenubarSubContent,
  RadioGroup,
  RadioGroupItem,
} from "@nebutra/ui/primitives"

import {
  Card,
  CardHeader,
  CardBody,
  CardFooter,
  CardIcon,
  CardTitle,
  CardDescription,
  Terminal,
  TerminalHeader,
  TerminalBody,
  TerminalLine,
  CommandBox,
} from "@nebutra/ui/patterns"

// Common Lucide Icons used in documentation examples
import {
  User,
  UserCircle,
  CheckCircle2,
  Search,
  ChevronsUpDown,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  ChevronLeft,
  AlignCenter,
  AlignLeft,
  AlignRight,
  Bold,
  Italic,
  Underline,
  Edit2,
  Copy,
  Trash2,
  Link as LinkIcon,
  Check as CheckIcon,
  Lock,
  Bell,
  Clock,
  Mountain,
  Timer,
  Map as MapIcon,
  TrendingUp,
  Layers,
  FileCode,
  BookOpen,
  LayoutDashboard,
  Users,
  BarChart,
  Settings,
  Volume2,
  ShieldCheck,
  XCircle,
  AlertCircle,
  Zap,
  Laptop,
  Sparkles,
  CloudMoon,
  X,
  Plus,
  Minus,
} from "lucide-react"

const CommandMenu = {
  Root: CommandMenuRoot,
  Input: CommandMenuInput,
  List: CommandMenuList,
  Empty: CommandMenuEmpty,
  Group: CommandMenuGroup,
  Item: CommandMenuItem,
  Shortcut: CommandMenuShortcut,
  Separator: CommandMenuSeparator,
} as const

const ContextMenu = {
  Root: ContextMenuRoot,
  Trigger: ContextMenuTrigger,
  Content: ContextMenuContent,
  Group: ContextMenuGroup,
  Item: ContextMenuItem,
  Label: ContextMenuLabel,
  Separator: ContextMenuSeparator,
} as const

// Create a pseudo-Menu object from DropdownMenu primitives for the Docs
const Menu = {
  Root: DropdownMenu,
  Trigger: DropdownMenuTrigger,
  Content: DropdownMenuContent,
  Item: DropdownMenuItem,
  Label: DropdownMenuLabel,
  Separator: DropdownMenuSeparator,
  RadioGroup: DropdownMenuRadioGroup,
  RadioItem: DropdownMenuRadioItem,
  CheckboxItem: DropdownMenuCheckboxItem,
  Sub: DropdownMenuSub,
  SubTrigger: DropdownMenuSubTrigger,
  SubContent: DropdownMenuSubContent,
} as const

const Combobox = Object.assign(ComboboxRoot, {
  Input: ComboboxInput,
  Option: ComboboxOptionItem,
  Empty: ComboboxEmpty,
  Group: ComboboxGroupSub,
  Separator: ComboboxSeparatorComp,
})

export function useMDXComponents(components: MDXComponents): MDXComponents {
  const merged = {
    ...defaultComponents,
    ...ObsidianComponents,
    ...PythonComponents,

    // ─── Fumadocs Built-ins ────────────────────────────────────────────────────
    Callout,
    Files,
    Folder,
    File,
    TypeTable,
    ImageZoom,
    InlineTOC,
    Mermaid,
    GithubInfo,
    FeedbackBlock: (
      props: React.ComponentPropsWithoutRef<typeof FeedbackBlock>
    ) => <FeedbackBlock {...props} onSendAction={onBlockFeedbackAction} />,
    // Tabs (Fumadocs specific)
    Tab,
    Tabs: FumadocsTabs,
    TabsList: FumadocsTabsList,
    TabsTrigger: FumadocsTabsTrigger,
    TabsContent: FumadocsTabsContent,
    // Steps
    Step,
    Steps,
    // Accordion (Fumadocs specific)
    Accordion: FumadocsAccordion,
    Accordions: FumadocsAccordions,
    UIAccordion,

    // ─── MDX Compat Layer (Mintlify/Fumadocs) ─────────────────────────────────
    Tip,
    Warning,
    Info,
    Note,
    Check,
    AccordionGroup,
    Card: FumadocsCard,
    CardGroup: FumadocsCardGroup,
    // Standard
    Link,

    // ─── Demo Components ──────────────────────────────────────────────────────
    // Registry demos referenced in MDX (as ComponentPreview children or standalone)
    AvatarSizeDemo,
    AvatarFallbackDemo,
    AvatarGroupDemo,
    AvatarGitPlatformDemo,
    DiceBearAvatarDemo,
    ButtonDemo,
    CheckboxDemo,
    SwitchDemo,
    DialogDemo,
    InputBasicDemo,
    DatePickerDefaultDemo,
    DatePickerMinMaxDemo,
    ProgressBasicDemo,
    AnimatedCircularProgressBarDemo,
    DotPatternDemo,
    FlickeringGridDemo,
    // Non-registry demos (used directly in MDX)
    AvatarWithIconDemo,
    AvatarSmartGroupDemo,
    BadgeVariantsDemo,
    BadgeSizesDemo,
    BadgeIconDemo,
    BadgePillDemo,
    BadgeTableDemo,
    BadgeNotificationDemo,
    BadgeFeatureTagDemo,
    AvatarSmartGroup,
    CalendarMinMaxDemo,
    CalendarUnavailableDemo,
    InputOTPNumericDemo,
    CommandDialogDemo,
    ContextMenuDemo,
    ContextMenuWithIconsDemo,
    MacbookProDemo,
    SheetDemo,
    SheetSideDemo,
    SheetMobileDemo,

    // ─── Documentation Helpers ────────────────────────────────────────────────
    ComponentPreview,
    APIPage,
    IconGallery,
    ColorPalette,
    ColorUsageDemos,
    TypographyHierarchyDemos,
    TypeScaleDemo,
    CJKWeightDemo,
    BrandGradientsDemo,
    MotionDemos,
    IntroductionHero,
    LogoShowcase,
    BrandPhilosophyVisual,
    VisuallyHiddenDemo,
    FocusRingDemo,
    AriaPatternsDemo,
    MinTouchTargetDemo,
    PrefersReducedMotionDemo,
    ContrastRequirementsDemo,
    SkipLinkStyleDemo,
    CopywritingErrorsDemo,
    CopywritingEmptyStateDemo,
    CopywritingSuccessDemo,
    CopywritingDestructiveDemo,
    CopywritingButtonsDemo,
    CopywritingProgressDemo,
    CopywritingCapitalizationDemo,
    ThemeSwitcherDemo,
    ThemeColorsDemo,
    BrandOverridesDemo,
    ZIndexDemo,
    StandardGridDemo,
    DashboardGridDemo,
    SplitLayoutDemo,
    HexGridDemo,
    DotPatternCardDemo,
    FlickeringGridCardDemo,
    WarpBackgroundDemo,
    StarsCanvasDemo,
    GlassmorphismDemo,
    GridDemo,
    GridCell,
    ResizablePanelGroup,
    ResizablePanel,
    ResizableHandle,
    ScrollArea,
    ScrollBar,
    Toggle,
    ToggleGroup,
    ToggleGroupItem,
    BasePopoverDemo,
    DialogSuccessDemo,
    DialogDeactivateDemo,
    DialogPasswordDemo,
    DialogShareDemo,
    "CommandMenu.Root": CommandMenu.Root,
    "CommandMenu.Input": CommandMenu.Input,
    "CommandMenu.List": CommandMenu.List,
    "CommandMenu.Empty": CommandMenu.Empty,
    "CommandMenu.Group": CommandMenu.Group,
    "CommandMenu.Item": CommandMenu.Item,
    "CommandMenu.Shortcut": CommandMenu.Shortcut,
    "CommandMenu.Separator": CommandMenu.Separator,
    "ContextMenu.Root": ContextMenu.Root,
    "ContextMenu.Trigger": ContextMenu.Trigger,
    "ContextMenu.Content": ContextMenu.Content,
    "ContextMenu.Group": ContextMenu.Group,
    "ContextMenu.Item": ContextMenuItem,
    "ContextMenu.Label": ContextMenuLabel,
    "ContextMenu.Separator": ContextMenu.Separator,
    Menu: Menu as unknown as React.ComponentType<Record<string, unknown>>,
    "Menu.Root": Menu.Root,
    "Menu.Trigger": Menu.Trigger,
    "Menu.Content": Menu.Content,
    "Menu.Item": Menu.Item,
    "Menu.Label": Menu.Label,
    "Menu.Separator": Menu.Separator,
    "Menu.Sub": Menu.Sub,
    "Menu.SubTrigger": Menu.SubTrigger,
    "Menu.SubContent": Menu.SubContent,
    "Menu.RadioGroup": Menu.RadioGroup,
    "Menu.RadioItem": Menu.RadioItem,
    "Menu.CheckboxItem": Menu.CheckboxItem,

    // ─── Nebutra UI Primitives ────────────────────────────────────────────────
    // These allow direct rendering inside MDX without wrapper files
    NebutraAccordion: UIAccordion,
    AccordionItem,
    AccordionTrigger,
    AccordionContent,
    Alert,
    AlertTitle,
    AlertDescription,
    AlertIcon,
    AlertContent,
    AlertToolbar,
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
    AlertDialogTrigger,
    Avatar,
    AvatarImage,
    AvatarFallback,
    AvatarGroup,
    GitHubAvatar,
    GitLabAvatar,
    BitbucketAvatar,
    AvatarWithIcon,
    DiceBearAvatar,
    Badge,
    Breadcrumb,
    BreadcrumbList,
    BreadcrumbItem,
    BreadcrumbLink,
    BreadcrumbSeparator,
    BreadcrumbPage,
    BreadcrumbEllipsis,
    Table,
    TableHeader,
    TableBody,
    TableFooter,
    TableRow,
    TableHead,
    TableCell,
    TableCaption,
    Button,
    ButtonLink,
    Checkbox,
    CheckboxGroup,
    Combobox,
    Dialog,
    DialogTrigger,
    DialogContent,
    DialogHeader,
    DialogFooter,
    DialogTitle,
    DialogDescription,
    DialogClose,
    DialogOverlay,
    DialogPortal,
    Input,
    Label,
    Select,
    SelectGroup,
    SelectValue,
    SelectTrigger,
    SelectContent,
    SelectLabel,
    SelectItem,
    SelectSeparator,
    Switch,
    NebutraTabs: Tabs,
    NebutraTabsList: TabsList,
    NebutraTabsTrigger: TabsTrigger,
    NebutraTabsContent: TabsContent,
    Separator,
    Tooltip,
    TooltipTrigger,
    TooltipContent,
    TooltipProvider,
    ContextMenu: ContextMenu as unknown as React.ComponentType<
      Record<string, unknown>
    >,
    Progress,
    Skeleton,
    Slider,
    Textarea,
    Sheet,
    SheetPortal,
    SheetOverlay,
    SheetTrigger,
    SheetClose,
    SheetContent,
    SheetHeader,
    SheetFooter,
    SheetTitle,
    SheetDescription,
    Drawer,
    DrawerPortal,
    DrawerOverlay,
    DrawerTrigger,
    DrawerClose,
    DrawerContent,
    DrawerHeader,
    DrawerFooter,
    DrawerTitle,
    DrawerDescription,
    Popover,
    PopoverTrigger,
    PopoverContent,
    PopoverAnchor,
    DropdownMenu,
    DropdownMenuTrigger,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuCheckboxItem,
    DropdownMenuRadioItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuShortcut,
    DropdownMenuGroup,
    DropdownMenuPortal,
    DropdownMenuSub,
    DropdownMenuSubContent,
    DropdownMenuSubTrigger,
    DropdownMenuRadioGroup,
    Carousel,
    CarouselContent,
    CarouselItem,
    CarouselPrevious,
    CarouselNext,
    Calendar,
    RangeCalendar,
    Command,
    CommandDialog,
    CommandInput,
    CommandList,
    CommandEmpty,
    CommandGroup,
    CommandItem,
    CommandShortcut,
    CommandSeparator,
    CommandMenu: CommandMenu as unknown as React.ComponentType<
      Record<string, unknown>
    >,
    DatePicker,
    DateRangePicker,
    Collapsible,
    CollapsibleTrigger,
    CollapsibleContent,
    HoverCard,
    HoverCardTrigger,
    HoverCardContent,
    Pagination,
    PaginationContent,
    PaginationItem,
    PaginationLink,
    PaginationPrevious,
    PaginationNext,
    PaginationEllipsis,
    InputOTP,
    InputOTPGroup,
    InputOTPSlot,
    InputOTPSeparator,
    CardContent,
    NavigationMenu,
    NavigationMenuList,
    NavigationMenuItem,
    NavigationMenuContent,
    NavigationMenuTrigger,
    NavigationMenuLink,
    NavigationMenuIndicator,
    NavigationMenuViewport,
    navigationMenuTriggerStyle: () => navigationMenuTriggerStyle(),

    Menubar,
    MenubarMenu,
    MenubarTrigger,
    MenubarContent,
    MenubarItem,
    MenubarSeparator,
    MenubarLabel,
    MenubarCheckboxItem,
    MenubarRadioGroup,
    MenubarRadioItem,
    MenubarShortcut,
    MenubarSub,
    MenubarSubTrigger,
    MenubarSubContent,
    RadioGroup,
    RadioGroupItem,

    // ─── Nebutra UI Patterns ──────────────────────────────────────────────────
    NebutraCard: Card,
    CardHeader,
    CardBody,
    CardFooter,
    CardIcon,
    CardTitle,
    CardDescription,
    Terminal,
    TerminalHeader,
    TerminalBody,
    TerminalLine,
    CommandBox,

    // ─── Lucide Icons ─────────────────────────────────────────────────────────
    User,
    UserCircle,
    CheckCircle2,
    Search,
    ChevronsUpDown,
    ChevronDown,
    ChevronUp,
    ChevronRight,
    ChevronLeft,
    AlignCenter,
    AlignLeft,
    AlignRight,
    Bold,
    Italic,
    Underline,
    Edit2,
    Copy,
    Trash2,
    LinkIcon,
    CheckIcon,
    Lock,
    Bell,
    Clock,
    Mountain,
    Timer,
    MapIcon,
    TrendingUp,
    Layers,
    FileCode,
    BookOpen,
    LayoutDashboard,
    Users,
    BarChart,
    Settings,
    Volume2,
    ShieldCheck,
    XCircle,
    AlertCircle,
    Zap,
    Laptop,
    Sparkles,
    CloudMoon,
    X,
    Plus,
    Minus,

    // ─── Governance Components ────────────────────────────────────────────────
    StatusBadge,
    DeprecatedBanner,
    FigmaLink,

    ...components,
  }
  return merged
}

// Export a direct getter so MDX remote compiler can inject it without React hooks rules
export function getMDXComponents(): MDXComponents {
  return useMDXComponents({})
}
