apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: nebutra
  labels:
    app.kubernetes.io/name: billing-service
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: billing-service
  ports:
    - name: http
      port: 80
      # billing-service container listens on 8006
      targetPort: http
      protocol: TCP
