apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: nebutra
  labels:
    app.kubernetes.io/name: content-service
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: content-service
  ports:
    - name: http
      port: 80
      # content-service container listens on 8002
      targetPort: http
      protocol: TCP
