apiVersion: v1
kind: Service
metadata:
  name: landing-page
  namespace: nebutra
  labels:
    app.kubernetes.io/name: landing-page
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: landing-page
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
