apiVersion: v1
kind: Service
metadata:
  name: web3-service
  namespace: nebutra
  labels:
    app.kubernetes.io/name: web3-service
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web3-service
  ports:
    - name: http
      port: 80
      # web3-service container listens on 8005
      targetPort: http
      protocol: TCP
