#!/usr/bin/env node
/**
 * generate-palette.mjs
 *
 * Generates a complete brand-override.css from two hex colors.
 * No dependencies — pure Node.js.
 *
 * Usage:
 *   node scripts/generate-palette.mjs --primary=#0033FE --secondary=#0BF1C3
 *   node scripts/generate-palette.mjs --primary=#7C3AED --secondary=#F59E0B
 *
 * Output:
 *   Prints brand-override.css to stdout.
 *   Redirect to file: node scripts/generate-palette.mjs --primary=#7C3AED --secondary=#F59E0B > my-brand.css
 */

// ── Argument parsing ────────────────────────────────────────

const args = Object.fromEntries(
  process.argv.slice(2).map((arg) => {
    const [key, value] = arg.replace(/^--/, "").split("=");
    return [key, value];
  }),
);

const primary = args.primary ?? "#0033FE";
const secondary = args.secondary ?? "#0BF1C3";

if (!primary.match(/^#[0-9A-Fa-f]{6}$/) || !secondary.match(/^#[0-9A-Fa-f]{6}$/)) {
  console.error("Error: Colors must be 6-digit hex values, e.g. --primary=#0033FE");
  process.exit(1);
}

// ── Color math ──────────────────────────────────────────────

function hexToHsl(hex) {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0,
    s = 0;
  const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r:
        h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
        break;
      case g:
        h = ((b - r) / d + 2) / 6;
        break;
      case b:
        h = ((r - g) / d + 4) / 6;
        break;
    }
  }
  return [Math.round(h * 360), Math.round(s * 100), Math.round(l * 100)];
}

function hslToHex(h, s, l) {
  const sN = s / 100,
    lN = l / 100;
  const a = sN * Math.min(lN, 1 - lN);
  const f = (n) => {
    const k = (n + h / 30) % 12;
    const color = lN - a * Math.max(Math.min(k - 3, 9 - k, 1), -1);
    return Math.round(255 * color)
      .toString(16)
      .padStart(2, "0");
  };
  return `#${f(0)}${f(8)}${f(4)}`;
}

/**
 * Generate an 11-step scale from a base color.
 * Steps: 50, 100, 200, 300, 400, 500 (base), 600, 700, 800, 900, 950
 */
function generateScale(hex) {
  const [h, s, l] = hexToHsl(hex);
  // Lightness values for each step (50→950)
  const lightnesses = [
    97,
    93,
    85,
    75,
    62,
    l,
    Math.max(l - 10, 5),
    Math.max(l - 20, 3),
    Math.max(l - 30, 2),
    Math.max(l - 40, 1),
    Math.max(l - 50, 0),
  ];
  const steps = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
  return Object.fromEntries(
    steps.map((step, i) => [step, hslToHex(h, Math.min(s, 95), Math.max(lightnesses[i], 1))]),
  );
}

// ── Generate ────────────────────────────────────────────────

const primaryScale = generateScale(primary);
const secondaryScale = generateScale(secondary);

const pad = (n) => String(n).padEnd(3);

const output = `/**
 * brand-override.css — Generated by scripts/generate-palette.mjs
 *
 * Primary:   ${primary}
 * Secondary: ${secondary}
 *
 * Generated: ${new Date().toISOString().split("T")[0]}
 *
 * Import in your globals.css:
 *   @import "@nebutra/theme/themes.css";
 */

:root {
  /* PRIMARY BRAND SCALE (generated from ${primary}) */
${Object.entries(primaryScale)
  .map(([step, hex]) => `  --nebutra-blue-${pad(step)}: ${hex};`)
  .join("\n")}

  /* SECONDARY ACCENT SCALE (generated from ${secondary}) */
${Object.entries(secondaryScale)
  .map(([step, hex]) => `  --nebutra-cyan-${pad(step)}: ${hex};`)
  .join("\n")}

  /* Brand gradients (auto-derived from 500 values above) */
  --brand-gradient: linear-gradient(135deg, var(--nebutra-blue-500) 0%, var(--nebutra-cyan-500) 100%);
  --brand-gradient-reverse: linear-gradient(135deg, var(--nebutra-cyan-500) 0%, var(--nebutra-blue-500) 100%);
  --brand-gradient-vertical: linear-gradient(180deg, var(--nebutra-blue-500) 0%, var(--nebutra-cyan-500) 100%);
  --brand-gradient-radial: radial-gradient(circle, var(--nebutra-cyan-500) 0%, var(--nebutra-blue-500) 100%);
}
`;

process.stdout.write(output);
