import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts", "src/primitives/index.ts", "src/marketing/index.ts"],
  format: ["esm"],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  noExternal: ["../types/three-fiber"],
  external: [
    "react",
    "react-dom",
    "@nebutra/design-system",
    "next",
    "next/link",
    "@clerk/nextjs",
    "motion",
    "motion/react",
    "date-fns",
    "@heroui/calendar",
    "@internationalized/date",
    "@heroui/checkbox",
    "@heroui/slider",
    "@heroui/progress",
    "@heroui/switch",
    "three",
    "@react-three/fiber",
  ],
});
